apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nsanjula/argocd-app-config.git
    targetRevision: HEAD # Pointing to the last commit
    path: dev # Poiting to the dev folder which has all the yaml files
  destination:
    server: https://kubernetes.default.svc # Pointing the same cluster where Argo CD is running
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true # Create the namespace if it doesn't exist

    automated:
      selfHeal: true # Automatically sync the application if it goes out of sync
      prune: true # Automatically delete resources that are no longer defined in the source repository
